language: node_js
node_js:
  - lts/*
before_install:
  - export TZ='Asia/Shanghai' # 设置时区
install:
  - npm i yarn -g
  - yarn global add vuepress
script:
  - yarn build # 执行命令
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # travis服务上的token变量
  keep_history: true
  on:
    branch: master
